### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by tktkl** [fangjinuo/easyjson#13]
请问您后续项目都会使用easyjson吗？ 我最近也觉得json做成门面模式可以快速切换依赖，比如遇到某些json第三方包漏洞问题且无法快速修复时， 自己改依赖比较快， 与springboot集成会更方便， 您觉得有必要吗？

**Comment by fangjinuo** [comment]
我们的项目中，目前已经都是用 的 easyjson API，就是出于这个考虑

**Comment by fangjinuo** [comment]
最近又花时间，将fastjson对jsontype，jsonfield给支持上了，这样用fastjson对应用适配到其他的json吕时，支持的场景更加丰富了

**Comment by langzhigang** [comment]
请教一下，楼主是如何处理不同json框架之间差异的问题。
比如fastjson 和 jackson 对 null的处理不同。

**Comment by fangjinuo** [comment]
> 请教一下，楼主是如何处理不同json框架之间差异的问题。
> 比如fastjson 和 jackson 对 null的处理不同。

这是个好问题，在JSONBuilder里会对这些特性做统一化配置，然后在各种底层json库会做相应的特性定制化实现，两者结合来保障与各种底层库结合时的统一行为

**Comment by tktkl** [comment]
注解要如何支持呢？ 比如jackson的@JsonProperty之类的。

**Comment by fangjinuo** [comment]
> 注解要如何支持呢？ 比如jackson的@JsonProperty之类的。

@tktkl 

目前还没有支持 把 gson, jackson 的 也通过 easyjson-core 去进行适配。
fastjson的都已经做好适配，它里的 \@JSONType, @JSONField 注解中的大部分常用属性已经进行了适配
