### ISSUE TITLE
Timestamp字段反序列化失败

### ISSUE THREAD

**Issue by chenlesky** [fangjinuo/easyjson#20]
项目中使用如下依赖来替换fastjson
   
        <dependency>
            <groupId>com.github.fangjinuo.easyjson</groupId>
            <artifactId>fastjson-to-easyjson</artifactId>
        </dependency>

        
        <dependency>
            <groupId>com.github.fangjinuo.easyjson</groupId>
            <artifactId>easyjson-jackson</artifactId>
        </dependency>

使用com.alibaba.fastjson.JSON.parseObject(str,A.class)
如果A中包含java.sql.Timestamp字段则会提示类型不匹配

**Comment by zhu04303661** [comment]
meet the same issue， could  some one fix it？

**Comment by fangjinuo** [comment]
@zhu04303661 @chenlesky 
问题已修复。有点晚，抱歉。
由于开源项目众多，如果只是在github上创建issue，可能没能及时看到。
建议的做法是：在github创建 issue后，加入QQ群，直接在群里把问题说一下。这样就能更快的修复了
