### ISSUE TITLE
jsonTreeNode调用ToString方法时输出格式错误

### ISSUE THREAD

**Issue by ha0yc** [fangjinuo/easyjson#22]
hey，最近在使用jackson桥接easyjson，测试过程中发现，调用JsonTreeNode.toString方法时，输出的是{"key":value}的形式，反序列化的话就会报错。
看了下toString源码：
`@Override
    public String toString() {
        ...
        //这里
        if (isJsonPrimitiveNode()) {
            return getAsString();
        }
       ...
        if (isJsonObjectNode()) {
            JsonObjectNode jsonObjectNode = getAsJsonObjectNode();
            StringBuilder b = new StringBuilder();
            b.append("{");
            Iterator<Map.Entry<String, JsonTreeNode>> iter = jsonObjectNode.propertySet().iterator();
            while (iter.hasNext()) {
                Map.Entry<String, JsonTreeNode> property = iter.next();
                b.append("\"").append(property.getKey()).append("\": "); // key
                b.append(property.getValue().toString());
                if (iter.hasNext()) {
                    b.append(", ");
                }
            }
            b.append("}");
            return b.toString();
        }
        return JSONBuilderProvider.simplest().toJson(this);
    }`
是在递归调用value的toString的时候没加引号，导致value格式错误
请看一下，是否确实有这个问题，多谢

**Comment by fangjinuo** [comment]
问题已修复： bc0d81baa5f500ddcaa7a0c5971f586dd85bbb23

但是这个 API不是这么用的。
